version: '3.8'

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/aagouzou/data/wp
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/aagouzou/data/db
      o: bind
      type: none

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
networks:
  inception:
    name: inception